//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shcool_event_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QTVAdminDangNhapLog
    {
        public long Id { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string TenDN { get; set; }
        public string MaQTV { get; set; }
        public Nullable<int> Quyen { get; set; }
        public string DiaChiIP { get; set; }
        public string ThietBi { get; set; }
    }
}
