//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shcool_event_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanTriVien
    {
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public int Quyen { get; set; }
        public string MaQTV { get; set; }
        public bool TrangThaiKhoa { get; set; }
    
        public virtual Vien Vien { get; set; }
    }
}
